### ISSUE TITLE
REDIS JSON

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/sweatShop-analyze#3]
TEST IF ITS AN GENERAL OPTION FOR OUR SERVICES

**Comment by patrick-hermann-sva** [comment]
https://github.com/nitishm/go-rejson

https://itnext.io/storing-go-structs-in-redis-using-rejson-dab7f8fc0053

**Comment by patrick-hermann-sva** [comment]
# REDIS STACK 

redis stack provides redis json and a nice ui for exporing sets/json/hashes etc.

```
sudo nerdctl run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
```

example go code (w/o the useless flush!)

```
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"

	"github.com/gomodule/redigo/redis"
	"github.com/nitishm/go-rejson/v4"
	goredis "github.com/redis/go-redis/v9"
)

var ctx = context.Background()

// Name - student name
type Name struct {
	First  string `json:"first,omitempty"`
	Middle string `json:"middle,omitempty"`
	Last   string `json:"last,omitempty"`
}

// Student - student object
type Student struct {
	Name Name `json:"name,omitempty"`
	Rank int  `json:"rank,omitempty"`
}

func Example_JSONSet(rh *rejson.Handler) {

	student := Student{
		Name: Name{
			"Mark",
			"S",
			"Pronto",
		},
		Rank: 1,
	}
	res, err := rh.JSONSet("student", ".", student)
	if err != nil {
		log.Fatalf("Failed to JSONSet")
		return
	}

	if res.(string) == "OK" {
		fmt.Printf("Success: %s\n", res)
	} else {
		fmt.Println("Failed to Set: ")
	}

	studentJSON, err := redis.Bytes(rh.JSONGet("student", "."))
	if err != nil {
		log.Fatalf("Failed to JSONGet")
		return
	}

	readStudent := Student{}
	err = json.Unmarshal(studentJSON, &readStudent)
	if err != nil {
		log.Fatalf("Failed to JSON Unmarshal")
		return
	}

	fmt.Printf("Student read from redis : %#v\n", readStudent)
}

func main() {
	var addr = flag.String("Server", "localhost:6379", "Redis server address")

	rh := rejson.NewReJSONHandler()
	flag.Parse()

	// Redigo Client
	conn, err := redis.Dial("tcp", *addr)
	if err != nil {
		log.Fatalf("Failed to connect to redis-server @ %s", *addr)
	}
	defer func() {
		// _, err = conn.Do("FLUSHALL")
		err = conn.Close()
		if err != nil {
			log.Fatalf("Failed to communicate to redis-server @ %v", err)
		}
	}()
	rh.SetRedigoClient(conn)
	fmt.Println("Executing Example_JSONSET for Redigo Client")
	Example_JSONSet(rh)

	// GoRedis Client
	cli := goredis.NewClient(&goredis.Options{Addr: *addr, DB: 0})

	rh.SetGoRedisClient(cli)
	fmt.Println("\nExecuting Example_JSONSET for Redigo Client")
	Example_JSONSet(rh)
}
```

**Comment by patrick-hermann-sva** [comment]
![image](https://github.com/stuttgart-things/sweatShop-analyzer/assets/47567770/66bb9f92-bcb4-4243-ad7d-17fb4b2202a4)

**Comment by xlai89** [comment]
* Some methods are added in `redis_json.go` and tested in  `redis_json_test.go`.
* The analyzed result can be saved as redis JSON unter the key `analyzerresult|my-repo-url`.
* Redis JSON does not expire. Instead, it has a `JSONDel` method.
* About the connection to redis server, there are two ways. 
  * One with go redis client using `"github.com/go-redis/redis/v8"` package, 
  * the other using redigo connection from `"github.com/gomodule/redigo/redis"`.
  * **Attention**: Cannot use `"github.com/redis/go-redis/v9"` for creating a redis JSON handler, because only `"github.com/go-redis/redis/v8"`  is supported:
![image](https://github.com/stuttgart-things/sweatShop-analyzer/assets/62478312/cd413295-f5df-42ee-91e7-130899bd5998)
@patrick-hermann-sva , can you confirm that?

**Comment by patrick-hermann-sva** [comment]
* For storing in redis-json i added the function SetObjectToRedisJSON (https://github.com/stuttgart-things/sthingsCli/blob/main/redis.go) - will use that in sweatShop-server and might some other services
* how would you suggest to work w/ JSONDel (didn't think of that usecase yet) / how does it work?
* w/ 
```
go get github.com/nitishm/go-rejson/v4@master
```
-> go mod will be updated and it should be possible to use v9 of go-redis (go.mod = github.com/nitishm/go-rejson/v4 v4.1.1-0.20230331060235-d2aa875760e4)

**Comment by xlai89** [comment]
* yep, `SetAnalyzerResult` is quite similar to your function.
* About `JSONDel` ([example](https://github.com/stuttgart-things/sweatShop-analyzer/blob/main/analyzer/redis_json.go#L116)), we won't need it for analyzer. I mentioned it, because the "go-rejson" library cannot set TTL for JSON yet (which we may or may not want to set). But just for our information. And by the way, TTL can be set to JSON via Redis Stack GUI but not sure how.
* Thanks for the tip! After upgrading "go-rejson" to master branch, it works well with v9. The analyzer code is updated.

**Comment by patrick-hermann-sva** [comment]
i think we will discuss a need of redis persistence in the future. we will go with redis json & streams for this service (for now). than you for testing / coding. issue closed.
